### ISSUE TITLE
Move FETCH_* option from advance() to getCurrent()

### ISSUE THREAD

**Issue by kelunik** [amphp/sql#4]
Instead of passing the `FETCH_*` constants to `advance()`, they should be passed to `ResultSet::getCurrent()`.

**Comment by kelunik** [comment]
Done via https://github.com/amphp/sql/commit/6b4e05f0450e94b0c93a0b376055fdc7d94cacfb.

**Comment by prolic** [comment]
second commit 9b667bafdfe6028e89ca0c1101354a7c3da8e032
